@startuml
title System-Navigation Package Diagram
package fast::rf_ros::NavigationSystem #LightYellow;line:blue {
    namespace NavigationExecutorSubsystem #LimeGreen {
        namespace DriveExecutor #LimeGreen {
                 class TankDriveExecutorNode #LimeGreen {}
        }
    }
}
@enduml