@startuml
title System-BaseMachine Package Diagram
package fast::rf_ros::BaseMachineSystem #LightYellow;line:blue {
    namespace BaseMachineSubsystem #LimeGreen {
        class ServoHatNode #LimeGreen
    }
}
@enduml