@startuml
title JoystickCalibration Node Class Diagram

namespace ros {
}
namespace fast::rf {
    namespace UserInterfaceSystem {
        namespace RemoteControlSubsystem {
        }
    }
}
namespace fast::rf_ros {
   namespace UserInterfaceSystem {
        package RemoteControlSubsystem #LightYellow;line:blue {
            class JoystickCalibrationNode #Yellow {
                -JoystickCalibrationProcess process
            }
            JoystickCalibrationNode --> JoystickCalibrationProcess: <<use>>
        }
    }
}
@enduml
        