' @compare_tag Node-ClassDiagram
@startuml
title JoystickCalibration Node Class Diagram

namespace ros {
}
namespace fast::rf {
    namespace UserInterfaceSystem {
        namespace RemoteControlSubsystem {
            namespace TeleopControl {

            }
        }
    }
}
namespace fast::rf_ros {
   namespace UserInterfaceSystem {
        namespace RemoteControlSubsystem {
            package TeleopControl #LightYellow;line:blue {
                class JoystickCalibrationNode #LimeGreen {
                }
            }
        }
    }
}
@enduml
        