@startuml
title InertialSensorFuser Node Class Diagram

namespace ros {
    class Subscriber
    class Publisher
    namespace sensor_msgs {
        class Imu <<(M,#FFFF00)>> <<ROS>>
    }
}
namespace fast::rf {
    namespace messages {
        namespace SensorMsgs {
            class ImuMsg <<(M,#FFFF00)>>
        }
    }
    namespace PoseSystem {
        namespace LocalPoseSubsystem {
            namespace InertialSensorFuser {
                interface IInertialSensorFuserProcess
                class BasicInertialSensorFuserProcess
                BasicInertialSensorFuserProcess -up-|> IInertialSensorFusersProcess
            }
            namespace LocalPoseFuser {

            }
        }
    }
}
namespace fast::rf_ros {
   namespace PoseSystem {
        namespace LocalPoseSubsystem {
            package  InertialSensorFuser #LightYellow;line:blue {
                class InertialSensorFuserNode <<ROS>> #LimeGreen {
                    -IInertialSensorFuserProcess process
                    -void IMU_Callback()
                    -Subscriber imu_sub
                    -Publisher machine_inertial_pub
                }
                InertialSensorFuserNode --> IInertialSensorFuserProcess: <<use>>
                InertialSensorFuserNode *-> BasicInertialSensorFuserProcess
            }

        }
    }
}
@enduml
        