@startuml
title NavigationExecutor Subsystem Class Diagram

namespace fast::rf_ros {
    namespace NavigationSystem {
        package NavigationExecutorSubsystem #LightYellow;line:blue {
            namespace DriveExecutor #LimeGreen {
                 class TankDriveExecutorNode #LimeGreen {}
            }
        }
    }
}
@enduml