@startuml
title System Monitor Class Diagram
namespace fast::rf {
    namespace messages {
        namespace InfrastructureMsgs {
            class ArmCommandMsg <<(M,#FFFF00)>>
        }
    }
}
namespace robot_framework_ros {
    class arm_command <<(M,#FFFF00)>> <<ROS>>
    class heartbeat <<(M,#FFFF00)>> <<ROS>>
    class ready_to_arm <<(M,#FFFF00)>> <<ROS>>
    class diagnostic <<(M,#FFFF00)>> <<ROS>>
}
namespace ncurses {
    class WINDOW
}
namespace fast::rf_ros {
    namespace utils {
        class CoreUtility
        class TranslateUtility
    }
    class BaseNode
    namespace Tools::Applications {
        package SystemMonitor #LightYellow;line:blue {
            namespace Definitions {
                enum Color #LimeGreen
                struct ScreenCoordinatePerc #Orange {
                    +double start_x_perc
                    +double start_y_perc
                    +double width_perc
                    +double height_perc
                }
                struct ScreenCoordinatePixel #Orange {
                    +uint16 start_x_pix
                    +uint16 start_y_pix
                    +uint16 width_pix
                    +uint16 height_pix

                }
                struct Key
            }
            interface IWindow #Orange {
                +{abstract} string get_name()
                +{abstract} bool is_initialized()
                +{abstract} bool update(double current_time_sec)
                +{abstract} string pretty()
                +{abstract} bool has_focus()
                +{abstract} bool set_focus(bool cmd_focus)
                ---Messages To Implment---
                +{abstract} void new_ArmCommandMsg(arm_command msg)
                +{abstract} void new_HeartbeatMsg(heartbeat msg)
                +{abstract} void new_ReadyToArmMsg(ready_to_arm msg)
                +{abstract} void new_DiagnosticMsg(diagnostic msg)
            }
            abstract BaseWindow #Orange {
                +BaseWindow(string name, \n int16 tab_order, \n double start_x_perc, \n double start_y_perc)
                +bool is_initialized()
                +string get_name()
                +bool has_focus()
                +bool set_focus(bool cmd_focus)
                #bool update(double current_time_sec)
                #{abstract} bool update_window()
                #string pretty()
                #void set_window(WINDOW win)
                #WINDOW get_window()
                #void set_screen_coordinates(ScreenCoordinatePixel coord)
                #ScreenCoordinatePerc get_screen_coordinates_perc()
                #ScreenCoordinatePixel get_screen_coordinates_pixel()
                #int16 get_tab_order()
                #void update_record_count(uint16 count)
                #double get_current_time_sec()
                
                -WINDOW win
                -string name
                -int16 tab_order
                -ScreenCoordinatePerc screen_coord_perc
                -ScreenCoordinatePixel get_screen_coordinates_pixel
                -uint16 mainwindow_height
                -uint16_t mainwindow_width
                -bool focused
                -int[] supported_keys
                -double current_time_sec_
                -uint16 record_count
            }
            BaseWindow .up.|> IWindow
            BaseWindow --> ScreenCoordinatePerc: <<use>>
            BaseWindow --> ScreenCoordinatePixel: <<use>>

            class HeaderWindow #Orange {
                +{static} double START_X_PERC
                +{static} double START_Y_PERC
                +{static} double WIDTH_PERC
                +{static} double HEIGHT_PERC
                +string pretty()
                +bool update(double current_time_sec)
                +void new_ArmCommandMsg(arm_command msg)
                +void new_HeartbeatMsg(heartbeat msg)
                +void new_ReadyToArmMsg(heartbeat msg)
                +void new_DiagnosticMsg(diagnostic msg)
                #bool update_window()
                -ArmCommandMsg latest_arm_command
            }
            HeaderWindow -up-|> BaseWindow
            enum NodeType #LimeGreen {
                UNKNOWN = 0,
                FAST = 1,
                NON_FAST = 2
            }
            enum NodeFieldColumn #Orange {
                MARKER = 0,
                ID = 1,
                HOSTNAME = 2,
                NODENAME = 3,
                STATUS = 4,
                READY_TO_ARM = 5,
                RESTARTS = 6,
                PID = 7,
                CPU = 8,
                RAM = 9,
                RX = 10

            }
            struct NodeData {
                +bool initialized
                +uint16 id
                +nodestate state
                +NodeType type
                +uint16 pid
                +string host_device
                +string base_node_name
                +string node_name
                +double cpu_used_perc
                +double mem_used_perc
                +double last_heartbeat
                +double last_heartbeat_delta
                +uint64 restart_count
            }
            NodeData --> NodeType: <<use>>
            class NodeInfoWindow #Orange {
                +{static} double START_X_PERC
                +{static} double START_Y_PERC
                +{static} double WIDTH_PERC
                +{static} double HEIGHT_PERC
                +string pretty()
                +bool update(double current_time_sec)
                +void new_ArmCommandMsg(arm_command msg)
                +void new_HeartbeatMsg(heartbeat msg)
                +void new_ReadyToArmMsg(heartbeat msg)
                +void new_DiagnosticMsg(diagnostic msg)
                #bool update_window()
                -bool insertNode(NodeType node_type,string device, string base_node_name, string node_name)
                -string get_window_header()

            }
            NodeInfoWindow +-- NodeType
            NodeInfoWindow +-- NodeFieldColumn
            NodeInfoWindow +-- NodeData
            NodeInfoWindow -up-|> BaseWindow
            class DeviceInfoWindow  {
                +{static} double START_X_PERC
                +{static} double START_Y_PERC
                +{static} double WIDTH_PERC
                +{static} double HEIGHT_PERC
                +string pretty()
                +bool update(double current_time_sec)
                +void new_ArmCommandMsg(arm_command msg)
                +void new_HeartbeatMsg(heartbeat msg)
                +void new_ReadyToArmMsg(heartbeat msg)
                +void new_DiagnosticMsg(diagnostic msg)
                #bool update_window()
            }
            DeviceInfoWindow -up-|> BaseWindow
            class NodeDiagnosticMonitor {
                +diagnostic node_diagnostic
                +double last_update_sec
                +double last_update_delta_sec
            }
            class DiagnosticWindow #Orange {
                +{static} double START_X_PERC
                +{static} double START_Y_PERC
                +{static} double WIDTH_PERC
                +{static} double HEIGHT_PERC
                +string pretty()
                +bool update(double current_time_sec)
                +void new_ArmCommandMsg(arm_command msg)
                +void new_HeartbeatMsg(heartbeat msg)
                +void new_ReadyToArmMsg(heartbeat msg)
                +void new_DiagnosticMsg(diagnostic msg)
                #bool update_window()
                -NodeDiagnosticMonitor[] node_diagnostic_monitors
            }
            DiagnosticWindow +-- NodeDiagnosticMonitor
            DiagnosticWindow -up-|> BaseWindow

            class StatusWindow #Orange {
                +{static} double START_X_PERC
                +{static} double START_Y_PERC
                +{static} double WIDTH_PERC
                +{static} double HEIGHT_PERC
                +string pretty()
                +bool update(double current_time_sec)
                +void new_ArmCommandMsg(arm_command msg)
                +void new_HeartbeatMsg(heartbeat msg)
                +void new_DiagnosticMsg(diagnostic msg)
                #bool update_window()
            }
            StatusWindow -up-|> BaseWindow

            class MenuWindow {
                +{static} double START_X_PERC
                +{static} double START_Y_PERC
                +{static} double WIDTH_PERC
                +{static} double HEIGHT_PERC
                +string pretty()
                +bool update(double current_time_sec)
                +void new_ArmCommandMsg(arm_command msg)
                +void new_HeartbeatMsg(heartbeat msg)
                +void new_DiagnosticMsg(diagnostic msg)
                #bool update_window()
            }
            MenuWindow -up-|> BaseWindow

            class SystemMonitorNode #Orange {
                -bool rescan_rosnetwork()
                -void arm_command_callback(arm_command msg)
                -void heartbeat_Callback(heartbeat msg)
                -void ready_to_arm_Callback(heartbeat msg)
                -void diagnostic_Callback(diagnostic msg)
                -bool update_monitorlist(string[] heartbeat_list, \nstring[] new_heartbeat_topics_to_subscribe, \nstring[] readytoarm_list, \nstring[] new_readytoarm_topics_to_subscribe, \n diagnostic_list, \n new_diagnostic_topics_to_subscribe)
                -IWindow[] windows
                -ros::Subscriber arm_command_sub
                -string[] monitored_heartbeat_topics
                -ros::Subscriber[] heartbeat_subs
                -string[] monitored_readytoarm_topics
                -ros::Subscriber[] readytoarm_subs
                -string[] monitored_diagnostic_topics
                -ros::Subscriber[] diagnostic_subs
            }
            SystemMonitorNode -up-|> BaseNode
            SystemMonitorNode *-up-> HeaderWindow
            SystemMonitorNode *-up-> NodeInfoWindow
            SystemMonitorNode *-up-> DeviceInfoWindow
            SystemMonitorNode *-up-> DiagnosticWindow
            SystemMonitorNode *-up-> StatusWindow
            SystemMonitorNode *-up-> MenuWindow

        }
    }
}
@enduml