' @compare_tag Node-ClassDiagram v0.1
@startuml
title InertialSensor Subsystem Class Diagram

namespace fast::rf_ros {
    namespace Pose {
        package InertialSensorSubsystem  #LightYellow;line:blue {
            class IMUNode <<ROS>> #Orange {

            }
        }
    }
}
@enduml
