@startuml
title RemoteControl Subsystem Class Diagram

namespace fast::rf_ros {
    namespace UserInterfaceSystem {
        package RemoteControlSubsystem #LightYellow;line:blue  {
            namespace TeleopControl {
                class BasicTeleopControlNode #LimeGreen {}
            }
        }
    }
}
@enduml