@startuml
title RemoteControl Subsystem Class Diagram

namespace fast::rf_ros {
    namespace UserInterfaceSystem {
        package RemoteControlSubsystem #LightYellow;line:blue  {
            class BasicTeleopControlNode #LimeGreen {}
        }
    }
}
@enduml