@startuml
title ServoHat Node Class Diagram
namespace fast::rf {
    namespace BaseMachineSystem {
        namespace BaseMachineSubsystem {
            class ServoHatProcess #LimeGreen
        }
    }
}
namespace fast::rf_ros {
   namespace BaseMachineSystem {
        package BaseMachineSubsystem #LightYellow;line:blue {
            class ServoHatNode #LimeGreen {
                -ServoHatProcess process
            }
            ServoHatNode --> ServoHatProcess: <<use>>
        }
    }
}
@enduml
        