@startuml
title System-Safety Package Diagram
package fast::rf_ros::SafetySystem #LightYellow;line:blue {
    namespace ModeManagerSubsystem #Orange {
        namespace ArmedStateManager #LimeGreen {
            class ArmedStateManagerNode <<ROS>> #LimeGreen {
            }
        }
    }
}
@enduml