@startuml
title System-UserInterface Package Diagram
package fast::rf_ros::UserInterfaceSystem #LightYellow;line:blue {
    namespace RemoteControlSubsystem #LimeGreen  {
        class BasicTeleopControlNode #LimeGreen {}
    }
}
@enduml