@startuml
title System-UserInterface Package Diagram
package fast::rf_ros::UserInterfaceSystem #LightYellow;line:blue {
    namespace RemoteControlSubsystem #LimeGreen  {
        namespace TeleopControl {
            class BasicTeleopControlNode #LimeGreen {}
        }
    }
}
@enduml