@startuml
title BaseMachine Subsystem Class Diagram

namespace fast::rf_ros {
    namespace BaseMachineSystem {
        package BaseMachineSubsystem #LightYellow;line:blue {
            class ServoHatNode #LimeGreen
        }
    }
}
@enduml