@startuml
title ROS Robot Framework Package Diagram
package fast::rf_ros #LightYellow;line:blue {
    namespace NavigationSystem #LimeGreen {
        namespace NavigationExecutorSubsystem #LimeGreen {
            namespace DriveExecutor #LimeGreen {
                 class TankDriveExecutorNode #LimeGreen {}
            }
        }
    }
    namespace UserInterfaceSystem #LimeGreen {
        namespace RemoteControlSubsystem #LimeGreen  {
            class BasicTeleopControlNode #LimeGreen {}
        }
    }
    namespace BaseMachineSystem #LimeGreen {
        namespace BaseMachineSubsystem #LimeGreen {
            class ServoHatNode #LimeGreen
        }
    }
}
@enduml