@startuml
title ROS Robot Framework Package Diagram
namespace fast::rf_ros {
    namespace NavigationSystem #Orange {
        
    }
    namespace UserInterfaceSystem #Orange {
        
    }
}
@enduml