@startuml
title Tank Drive Executor Node Class Diagram

namespace ros {
  namespace geometry_msgs {
      class Twist <<(M,#FFFF00)>> <<ROS>>
  }
}
namespace fast::rf {
    namespace NavigationSystem {
        namespace NavigationExecutorSubsystem {
            interface IDriveExecutorProcess #LimeGreen {}
            interface IDriveExecutorOutput #LimeGreen {}
            class TankDriveExecutorProcess #LimeGreen {}
            class TankDriveExecutorOutput #LimeGreen {}
            TankDriveExecutorProcess -up-|> IDriveExecutorProcess
            
            TankDriveExecutorOutput -up-|> IDriveExecutorOutput
            TankDriveExecutorProcess --> TankDriveExecutorOutput: <<use>>
        }
    }
}
namespace fast::rf_ros {
   namespace NavigationSystem {
        package NavigationExecutorSubsystem #LightYellow;line:blue {
            class TankDriveExecutorNode #LimeGreen {
                -TankDriveExecutorProcess process
            }
            TankDriveExecutorNode --> TankDriveExecutorProcess: <<use>>
            TankDriveExecutorNode --> TankDriveExecutorOutput: <<use>>
            TankDriveExecutorNode --> Twist: <<depend>>
        }
    }
}
@enduml
        