@startuml
title Basic Teleop Control Node Class Diagram

namespace ros {
  namespace geometry_msgs {
    class Twist <<(M,#FFFF00)>> <<ROS>>
  }
  namespace sensor_msgs {
    class Joy <<(M,#FFFF00)>> <<ROS>>
  }
}
namespace robot_framework_ros {
    class BaseNode
    class arm_command <<(M,#FFFF00)>> <<ROS>>
}
namespace fast::rf {
    namespace UserInterfaceSystem {
        namespace RemoteControlSystem {
            interface ITeleopControlProcess
            class BasicTeleopControlProcess
            BasicTeleopControlProcess -up-|> ITeleopControlProcess
        }
    }
}
namespace fast::rf_ros {
   namespace UserInterfaceSystem {
        package RemoteControlSystem #LightYellow;line:blue {
            class BasicTeleopControlNode #LimeGreen {
                -BasicTeleopControlProcess process
            }
            BasicTeleopControlNode -up-|> BaseNode
            BasicTeleopControlNode --> BasicTeleopControlProcess: <<use>>
            BasicTeleopControlNode --> Twist: <<depend>>
            BasicTeleopControlNode --> Joy: <<depend>>
        }
    }
}
@enduml
        