' @compare_tag Node-ClassDiagram v0.1
@startuml
title IMU Node Class Diagram

namespace ros {
    namespace sensor_msgs {
        class Imu <<(M,#FFFF00)>> <<ROS>>
        class MagneticField <<(M,#FFFF00)>> <<ROS>>
    }
}
namespace fast::rf {
    namespace PoseSystem {
        namespace InertialSensorSubsystem {
            namespace IMU {
                interface IIMUProcess
                class IMUProcess
                IMUProcess -up-|> IIMUProcess
                interface IIMUDriver
                IMUProcess --> IIMUDriver: <<use>>
                class MockIMUDriver
                MockIMUDriver -up-|> IIMUDriver
                class IMUSYDTM151Driver
                IMUSYDTM151Driver -up-|> IIMUDriver
                class IMURazor9DOFDriver
                IMURazor9DOFDriver -up-|> IIMUDriver
            }

        }
    }
}
namespace fast::rf_ros {
   namespace PoseSystem {
        namespace InertialSensorSubsystem {
            package IMU #LightYellow;line:blue {
                class IMUNode <<Orange>> #LimeGreen {
                    -IMUProcess process
                    -std::string imu_frame
                    -ros::Publisher imu_pub
                    -ros::Publisher magnetometer_pub
                }
                IMUNode --> IMUProcess: <<use>>
            }
        }
    }
}
@enduml
        
