@startuml
title Core Utility Class Diagram
namespace fast::rf_ros {
    namespace utils {
        class CoreUtility #Orange {
            +{static} double measure_time_diff(ros::Time time_a, ros::Time time_b)
        }
    }
}

@enduml