@startuml
title ArmedStateManager Node Class Diagram

namespace fast::rf {
    namespace SafetySystem {
        namespace ModeManagerSubsystem {
            namespace ArmedStateManager {
                class ArmedStateManagerProcess
            }
        }
    }
}
namespace fast::rf_ros {
   namespace SafetySystem {
        namespace ModeManagerSubsystem {
            package ArmedStateManager #LightYellow;line:blue {
                class ArmedStateManagerNode <<ROS>> #LimeGreen {
                    -ArmedStateManagerProcess process
                }
                ArmedStateManagerNode --> ArmedStateManagerProcess: <<use>>
            }
        }
    }
}
@enduml
        