' @compare_tag Node-ClassDiagram v0.1
@startuml
title {{cookiecutter.Node}} Node Class Diagram

namespace ros {
    class Subscriber
    class Publisher
}
namespace fast::rf {
    namespace {{cookiecutter.System}}System {
        namespace {{cookiecutter.Subsystem}}Subsystem {
            namespace {{cookiecutter.Node}} {
                
            }
        }
    }
}
namespace fast::rf_ros {
   namespace {{cookiecutter.System}}System {
        namespace {{cookiecutter.Subsystem}}Subsystem 
            package {{cookiecutter.Node}} { #LightYellow;line:blue {
                class {{cookiecutter.Node}}Node #Yellow {
                    -{{cookiecutter.Node}}Process process
                }
                {{cookiecutter.Node}}Node --> {{cookiecutter.Node}}Process: <<use>>
            }
        }
    }
}
@enduml
        