@startuml
title {{cookiecutter.Subsystem}} Subsystem Class Diagram

namespace fast::rf_ros {
    namespace {{cookiecutter.System}} {
        namespace {{cookiecutter.Subsystem}}Subsystem {
        }
    }
}
@enduml